version: "3.9"

services:
  postgres:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres123"
      POSTGRES_PASSWORD: "123postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4:8.12.0
      restart: always
      ports:
        - "8878:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: test@gmail.com
        PGADMIN_DEFAULT_PASSWORD: test
      volumes:
        - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:
