version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres123"
      POSTGRES_PASSWORD: "123postgres"
    ports:
      - "5432:5432"
