version: '3.8'

services:
  mongo:
    image: mongo:6.0.18
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hsa103
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=hsa103
    restart: always
  mongo-express:
    image: mongo-express:1.0.2-20
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hsa103
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
