version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:5.0.6
    ports:
      - 27017:27017
    restart: always
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
