version: '3.1'

services:

  db:
    image: mariadb:11.5
    ports:
      - 3306:3306
    volumes:
      - ./persistence_data/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sepersecuremariadbrootpassword
      MYSQL_PASSWORD: supersecuremariadbpassword
      MYSQL_USER: sepersecuremariadbuser
      MYSQL_DATABASE: seper_secure_db

